name: step_tracker_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  
  # firebase
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0

  # sign in
  google_sign_in: ^6.2.1


  # toast message
  fluttertoast: ^8.2.4

  # style
  # cupertino_icons: ^1.0.2d

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # linters
  very_good_analysis: ^5.1.0
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true